### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by heyitsmi** [Nazmul7989/laravel-facebook-post#4]
I want to schedule posting to a Facebook page; I use the command below.

```php
public function handle()
{
    $events = Event::whereDate('created_at', now()->toDateString())->get();
    // $events = Event::latest()->limit(5)->get();

    if($events->isEmpty()) {
        $this->info('No new event found today');
        return;
    }

    $text = "EVENT BARU HARI INI\n\n";

    foreach ($events as $event) {
        if ($event->categories) {
            $categories = $event->categories->map(function ($category) {
                return $category->name;
            })->implode(', ');
        } else {
            $categories = '-';
        }

        $text .= "<b>$event->name</b>\n\n"
            . "Kategori: $categories\n"
            . "Tanggal: $event->date\n"
            . "Lokasi: $event->location\n\n"
            . route('event-code', $event->code)
            . "\n\n===========\n\n";
    }

    $message = $text;

    $response = FacebookPost::storePost($message);

    $this->info($response);
}
```
When I run the command, I get an error like the one below.

```
[2024-08-05 15:53:26] local.ERROR: Array to string conversion {"exception":"[object] (ErrorException(code: 0): Array to string conversion at C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\InteractsWithIO.php:304)
[stacktrace]
#0 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Array to string...', 'C:\\\\laragon\\\\www\\\\...', 304)
#1 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\InteractsWithIO.php(304): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Array to string...', 'C:\\\\laragon\\\\www\\\\...', 304)
#2 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\InteractsWithIO.php(291): Illuminate\\Console\\Command->line(Array, 'info', NULL)
#3 C:\\laragon\\www\\infolari\\app\\Console\\Commands\\PostNewEventToFacebook.php(62): Illuminate\\Console\\Command->info(Array)
#4 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): App\\Console\\Commands\\PostNewEventToFacebook->handle()
#5 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#7 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(213): Illuminate\\Container\\Container->call(Array)
#10 C:\\laragon\\www\\infolari\\vendor\\symfony\\console\\Command\\Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(182): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 C:\\laragon\\www\\infolari\\vendor\\symfony\\console\\Application.php(1047): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 C:\\laragon\\www\\infolari\\vendor\\symfony\\console\\Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\PostNewEventToFacebook), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 C:\\laragon\\www\\infolari\\vendor\\symfony\\console\\Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(196): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 C:\\laragon\\www\\infolari\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1203): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 C:\\laragon\\www\\infolari\\artisan(13): Illuminate\\Foundation\\Application->handleCommand(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#18 {main}
"} 
```

How do I solve this issue?

**Comment by Nazmul7989** [comment]
@hilmihidyt  You are passing array instead of string. That's why it's throwing array to string conversion error. You must pass string in `storePost()` method. I wrote a example code based on your code and it's working fine. Here is the code:

``` 
$events = [
            [
                'name' => 'Event One',
                'date' => '2024-09-20 12:30:00',
                'location' => 'Dhaka Bangladesh',
                'code' => 'LDKF8343',
                'categories' => [
                    ['name' => 'Category one of Event One'],
                    ['name' => 'Category two of Event One'],
                ]
            ],
            [
                'name' => 'Event Two',
                'date' => '2024-09-20 12:30:00',
                'location' => 'Dhaka Bangladesh',
                'code' => 'LDKF8343',
                'categories' => [
                    ['name' => 'Category one of Event Two'],
                    ['name' => 'Category two of Event Two'],
                ]
            ]
        ];

        $events = collect($events);

        $text = "EVENT BARU HARI INI\n\n";

        foreach ($events as $event) {
            if ($event['categories']) {
                $categories = collect($event['categories'])->map(function ($category) {
                    return $category['name'];
                })->implode(', ');
            } else {
                $categories = '-';
            }

            $text .= "<b>{$event['name']}</b>\n\n"
                . "Kategori: $categories\n"
                . "Tanggal: {$event['date']}\n"
                . "Lokasi: {$event['location']}\n\n"
                . route('posts.show', $event['code'])
                . "\n\n===========\n\n";


        }

        $message = $text;
```

**Comment by heyitsmi** [comment]
@Nazmul7989 Thank you very much for your guide. Btw, when I try with the code as below;

```php
Route::get('test', function () {
    $events = [
        [
            'name' => 'Event One',
            'date' => '2024-09-20 12:30:00',
            'location' => 'Dhaka Bangladesh',
            'code' => 'LDKF8343',
            'categories' => [
                ['name' => 'Category one of Event One'],
                ['name' => 'Category two of Event One'],
            ]
        ],
        [
            'name' => 'Event Two',
            'date' => '2024-09-20 12:30:00',
            'location' => 'Dhaka Bangladesh',
            'code' => 'LDKF8343',
            'categories' => [
                ['name' => 'Category one of Event Two'],
                ['name' => 'Category two of Event Two'],
            ]
        ]
    ];

    $events = collect($events);

    $text = "EVENT BARU HARI INI\n\n";

    foreach ($events as $event) {
        if ($event['categories']) {
            $categories = collect($event['categories'])->map(function ($category) {
                return $category['name'];
            })->implode(', ');
        } else {
            $categories = '-';
        }

        $text .= "<b>{$event['name']}</b>\n\n"
            . "Kategori: $categories\n"
            . "Tanggal: {$event['date']}\n"
            . "Lokasi: {$event['location']}\n\n"
            . route('front.event-detail', $event['code'])
            . "\n\n===========\n\n";
    }

    $message = $text;

    $response = FacebookPost::storePost($message);

    dd($response);
});
```

I get an error message:

![image](https://github.com/user-attachments/assets/22819ea7-870d-42b4-aab8-98e8f0ad58d3)

**Comment by Nazmul7989** [comment]
@hilmihidyt This error is arising because of permission related issue of page. Please regenerate page access token and  try again. Don't forget to assign the bellow permissions while generating access token:
![Screenshot_1](https://github.com/user-attachments/assets/e2e9622c-b136-40e3-a993-2d2272906275)
